services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"
    volumes:
      - mydata:/data/db


volumes:
  mydata: